### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Alavaramantisi** [barismeral/Amazon-Nvidia-3070-3080-Autobuy-bot#1]
Merhaba,

Installation kısmındaki 3. adımı yapamadım sanırım. Yardımcı olabilir misiniz? Bir de buraya ekleyeceğimiz linkleri program sırayla mı kontrol ediyor acaba?

**Comment by barismeral** [comment]
Dosyaları klasör olarak indirdikten sonra 
Google Chrome uzantılar bölümüne gelip paketlenmiş uzantıyi yükle kısmından dosyanın yolunu Amazon klasörünú seçip tamam demen gerekiyor.

**Comment by Alavaramantisi** [comment]
![image](https://user-images.githubusercontent.com/64653569/111759815-118c6500-88af-11eb-9fdf-dd48f2ddd99f.png)
Bu işlemi yaptıktan sonra programı yine de çalıştıramadım.

**Comment by barismeral** [comment]
Yükleme tamam tanımlanan linkleri açın çalışacaktir, yeni bir sürümü yayınlayacağım linklerle uğraşmadan 3070 ve 3080 tüm ürünlerde çalışacak, sayfayı yenileyin ve tanımlı linkleri deneyin çalışacak sayfa yenileyecek

Android için Outlook<https://aka.ms/AAb9ysg>’u edinin

________________________________

**Comment by Alavaramantisi** [comment]
Evet çalıştı sanırım ben anlamamışım en başta programın nasıl çalıştığını. Teşekkür ederim. Yeni sürümü de bekliyorum o zaman 👍

**Comment by barismeral** [comment]
Repositorye yıldız verirsen sevinirim

Android için Outlook<https://aka.ms/AAb9ysg>’u edinin

________________________________

**Comment by Alavaramantisi** [comment]
Tüm linkleri ayrı ayrı açmam gerekiyor değil mi?
